   <!--footer contain social contact and -->
    <footer>
      <div class="socials">
            <a href="https://github.com/NyanPhyo/Group_Project_1-GP2.git" target="_blank"><img src="resources/images/github_icon.png" alt="github_icon" title="github.com"></a>
            <a href="https://aungkhantzaw1235.atlassian.net/jira/software/projects/TAOW/boards/34?atlOrigin=eyJpIjoiZjYyODczODA5NDNhNGYwMzgzZTRkYjRlMGY5MmQzZDgiLCJwIjoiaiJ9" target="_blank"><img src="resources/images/jira_icon.png" alt="jira_icon" title="jira.com"></a>
            <a href="mailto:info@3a1w.com" target="_blank"><img src="resources/images/email_icon.png" alt="mail_icon" title="gmail.com"></a>
        </div>
        <p class="credits">Credits to 'Freepik' for logo and 'UveshCreativeAssets' for banner video</p>
    </footer>
</body>
</html>
